% do_0c_bst_import_trigger_DuetEx.m

% running while opening the protocol 'Duet2017'

% modifiying for DuetReverb (451C W22)
% DuetDistance (451C W24) 2024-03-10
% Sunday, I am missing TF SubB 05

% modifying for Duet excersize (451C w26) 2026-01-27

% DrumDuetImprov 2026-03-08

% universal name
% list subj#1 subj#2 in the order of the file
pair = {
    'UV', 'ML';
    'LJ', 'TF';
    'CM', 'MG';
    };
npair = size(pair,1);

player = {'SubA';'SubB'};

% loop all the pairs
for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    % loop two partners
    for isubj=1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        display(playerID)
        All_sFiles = {
            sprintf('%s/@raw%s_01_%s_Data/data_0raw_%s_01_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_02_%s_Data/data_0raw_%s_02_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_03_%s_Data/data_0raw_%s_03_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_04_%s_Data/data_0raw_%s_04_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_05_%s_Data/data_0raw_%s_05_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_06_%s_Data/data_0raw_%s_06_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_07_%s_Data/data_0raw_%s_07_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_08_%s_Data/data_0raw_%s_08_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            };  
        nfile=size(All_sFiles,2);
        
        
        for ifile =1:nfile
            % current event file RawFiles
            
            % Linux now (it didn't run without .mat)
            %event_filename=sprintf('/user/t/takako/MATLAB/Duet/eeg_analysis/Duet2022/EventFiles/events_%s_run%d.mat',subjname, ifile);
            
            % PC (it didn't run without .mat)
            event_filename=sprintf('/Volumes/MLF/EEG-Hyperscanning/EX 2/EventFiles/events_%s_run%d.mat',subjname, ifile);
             
            RawFiles = {...
                event_filename;
                };
            
            % nofile? skip
            if ~exist(event_filename) 
                display(sprintf('%s: file not found', event_filename)); 
                continue;
            end
            
            
            % Script generated by Brainstorm (14-Jul-2021)
            % Start a new report
            % bst_report('Start', sFiles);      
          

            % EEG raw file
            my_current_eegfile = All_sFiles{ifile};

            sFiles = {...
                my_current_eegfile;
                };


            % Process: Import from file
            sFiles = bst_process('CallProcess', 'process_evt_import', sFiles, [], ...
                'evtfile', {RawFiles{1}, 'BST'}, ...
                'evtname', '', ...
                'delete',  0);
            
%             % Save and display report
%             ReportFile = bst_report('Save', sFiles);
%             bst_report('Open', ReportFile);
            % bst_report('Export', ReportFile, ExportDir);
            
        end % ifile
    end % isubj
end % ipair
