% do_0a_bst_linkraw_Duet.m

% Script generated by Brainstorm (03-Feb-2015)
% modified by Takako Fujioka 2015 March 3
% more modification for Duet study 2016 March 6
% brought back from Madeline's directory
% (Research/Motif_Piano_Duet/analysis_code) on 2019 01 27

% this will automatically make a new subject in the protocol and creat links to raw files, 
% but you have to import a
% channel file from 'channel_initial.mat'

%% for each pair, list the two people in the order that the filenames follow

% in Brainstorm make 'DrumDuetImprov' protocol

% this is where you store downloaded .cnt files (you have to change it
% yourself)
mydirname = '/Volumes/MLF/EEG-Hyperscanning/EX 2/EEG_raw';

% universal name

% list subj#1 subj#2 in the order of the file
pair = {
        'UV', 'ML';
        'LJ', 'TF'; 
        };    
npair = size(pair,1);

player = {'SubA';'SubB'};

for ipair = 1:npair

        sub={pair{ipair,1};pair{ipair,2}};
        pairname = sprintf('%s_%s', sub{1}, sub{2});
     
    for isubj=1:2
        if isubj==1
            subjname=sub{1};
            playerID=player{1};
        else
            subjname=sub{2};
            playerID=player{2};
        end

        % this assumes you have the 'raw' folder and four subfolders of
        % each person's name ('UV', 'ML' etc.)
    RawFiles = {...
        sprintf('%s/%s/%s_01_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_02_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_03_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_04_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_05_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_06_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_07_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        sprintf('%s/%s/%s_08_%s_Data.cnt',mydirname,subjname,pairname,playerID),...
        };
    
     

    nraw = size(RawFiles,2);
    
    
        for iraw = 1:nraw

            % Input files
            sFiles = [];

            % Start a new report
            bst_report('Start', sFiles);

            % Process: Create link to raw file
            sFiles = bst_process('CallProcess', 'process_import_data_raw', ...
                sFiles, [], ...
                'subjectname', sub{isubj}, ...
                'datafile', {RawFiles{iraw}, 'EEG-NEUROSCAN-CNT'}, ...
                'channelreplace', 0, ...
                'channelalign', 0);

            % Save and display report
            ReportFile = bst_report('Save', sFiles);
            % bst_report('Open', ReportFile);  % commented out: Java NullPointerException on macOS

        end
    end

 end

%% now import channel file from 'channel_initial.mat' because it is right now a wrong file 'CNT 2D channels (67)' 
% you have to import channels so that it has 'Neuroscan Quik-cap (67)'
