% do_0b_bst_ssp_Duet.m

% do_bst_ssp_2017Nov.m
% 2017 11 02 by Takako for Aury's analysis on the Duet data

% 2026 01 27 by Takako to offer a revised pipeline for 451C W26 analysis
% exercise

% Because the computation of SSP projectors are not anymore based on 
% blink epoched files, we are using only one of the continuous files
% to make projectors.

% Need to have detected eyeblinks within Brainstorm prior to this step

% Script generated by Brainstorm (18-May-2017)

% DrumDuetImprov 2026-03-08

% universal name
% list subj#1 subj#2 in the order of the file
pair = {
    'UV', 'ML';
    'LJ', 'TF';
    'CM', 'MG';
    };
npair = size(pair,1);

player = {'SubA';'SubB'};


% in this procedure only one raw file is looked at to do blink detections
% and SSP projector construction. All the other files can use these
% projectors later when epoching.
for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    for isubj= 1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        % List all the raw files for each subject
        % Input files

        % I am using only one of the 'computer-partner' files
        sFiles = {...
           sprintf('%s/@raw%s_01_%s_Data/data_0raw_%s_01_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
           };
        
        timeMax = 1800;
                
        % Start a new report
        bst_report('Start', sFiles);
        
        % Process: Detect eye blinks
        sFiles = bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
            'channelname', 'VEO', ...
            'timewindow',  [0, timeMax], ...
            'eventname',   'blinkv');
        
        % Process: Detect eye blinks
        sFiles = bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
            'channelname', 'HEO', ...
            'timewindow',  [0, timeMax], ...
            'eventname',   'blinkh');
        
        % Process: SSP EOG: blinkv
        sFiles = bst_process('CallProcess', 'process_ssp_eog', sFiles, [], ...
            'eventname',   'blinkv', ...
            'sensortypes', 'EEG', ...
            'usessp',      1, ...
            'select',      1);
        
        % Process: SSP EOG: blinkh
        sFiles = bst_process('CallProcess', 'process_ssp_eog', sFiles, [], ...
            'eventname',   'blinkh', ...
            'sensortypes', 'EEG', ...
            'usessp',      1, ...
            'select',      1);
        
        % Save and display report
        ReportFile = bst_report('Save', sFiles);
        % bst_report('Open', ReportFile);  % commented out: Java NullPointerException on macOS
        % bst_report('Export', ReportFile, ExportDir);
        
    end % subj 
end % pair

%% after this you should look at the projectors and make a good selections. 
% Remember, the effective projectors are straight line splits
% Also, an isolated small spot for one electrode is important