% do_1c_bst_import_continuous_DuetEx.m

% Script generated by Brainstorm (14-Jul-2021)
% Run this while Brainstorm opened

% this script imports the each of entire continuous file while applying SSP
% (eye artifact removal)

% DrumDuetImprov 2026-03-08

% universal name
% list subj#1 subj#2 in the order of the file
pair = {
    'UV', 'ML';
    'LJ', 'TF';
    };
npair = size(pair,1);
player = {'SubA';'SubB'};

for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    % loop two partners
    for isubj=1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        sFiles = {...
            sprintf('%s/@raw%s_01_%s_Data/data_0raw_%s_01_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_02_%s_Data/data_0raw_%s_02_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_03_%s_Data/data_0raw_%s_03_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_04_%s_Data/data_0raw_%s_04_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_05_%s_Data/data_0raw_%s_05_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_06_%s_Data/data_0raw_%s_06_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_07_%s_Data/data_0raw_%s_07_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            sprintf('%s/@raw%s_08_%s_Data/data_0raw_%s_08_%s_Data.mat',subjname,pairname,playerID,pairname,playerID), ...
            }; 

        
% Start a new report
bst_report('Start', sFiles);

% Process: Import MEG/EEG: Time
sFiles = bst_process('CallProcess', 'process_import_data_time', sFiles, [], ...
    'subjectname', subjname, ...
    'condition',   '', ...
    'timewindow',  [], ...
    'split',       0, ...
    'ignoreshort', 0, ...
    'usectfcomp',  0, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    []);

% Save and display report
ReportFile = bst_report('Save', sFiles);
% bst_report('Open', ReportFile);  % commented out: Java NullPointerException on macOS
% bst_report('Export', ReportFile, ExportDir);
    end % isubj
end % ipair
