% do_bst_epoch_avg_Duet_FRN.m
% 2015 Dec 20 by Takako Fujioka
% 2016 Mar 6 by Takako Fujioka
% 2017 Dec 7 by Madeline Huberth for FRN study
% 2019 Jan 27 brought back by Takako
% 2026 Jan 27 for 451C W26 Exercise

% DrumDuetImprov 2026-03-08

%% list all the pairs

pair = {
    'UV', 'ML';
    'LJ', 'TF';
    'CM', 'MG';
    };
npair = size(pair,1);
player = {'SubA';'SubB'};

for ipair = 1:npair
    
    sub={pair{ipair,1};
        pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    for isubj=1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        % List all the raw files for each subject (but applied
        % repair_steps)

% Path: C:\Users\tfujioka\Documents\brainstorm_db\DrumDuetImprov\data
% Name: LJ/LJ_TF_01_SubA_Data/data_block001_matlab.mat
   
         sFiles = {...
            sprintf('%s/%s_01_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_02_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_03_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_04_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_05_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_06_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_07_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            sprintf('%s/%s_08_%s_Data/data_block001.mat',subjname,pairname,playerID), ...
            };

        timemax = 1800;
        
        %         Process: Import MEG/EEG: Events
        sFiles = bst_process(...
            'CallProcess', 'process_import_data_event', ...
            sFiles, [], ...
            'subjectname', subjname, ...
            'condition', '', ...
            'eventname', 'DevSelfMytimbTwo, DevSelfPntimbTwo, DevOtherMytimbTwo, DevOtherPntimbTwo,DevSelfMytimbOne, DevSelfPntimbOne, DevOtherMytimbOne, DevOtherPntimbOne,StdSelfMytimbTwo, StdSelfPntimbTwo, StdOtherMytimbTwo, StdOtherPntimbTwo, StdSelfMytimbOne, StdSelfPntimbOne, StdOtherMytimbOne, StdOtherPntimbOne,' , ... 
            'timewindow', [0, timemax], ...
            'epochtime', [-0.5 1.0], ...
            'createcond', 1, ...
            'ignoreshort', 1, ...
            'usectfcomp', 1, ...
            'usessp', 0, ...
            'freq', [], ...
            'baseline', []);
        
        % Note that ssp is turned off because we already run it at the
        % first place
        
        % Process: Detect bad channels: Peak-to-peak  EEG(-250-250)
        sFiles = bst_process(...
            'CallProcess', 'process_detectbad', ...
            sFiles, [], ...
            'timewindow', [-0.2, 0.6], ...
            'meggrad', [0, 0], ...
            'megmag', [0, 0], ...
            'eeg', [-250, 250], ...
            'eog', [0, 0], ...
            'ecg', [0, 0], ...
            'rejectmode',  1);  % Reject only the bad channels
        
        % Process: Average: By condition (subject average)
        sFiles = bst_process(...
            'CallProcess', 'process_average', ...
            sFiles, [], ...
            'avgtype', 3, ...
            'avg_func', 1, ...  % <HTML>Arithmetic average: <FONT color="#777777">mean(x)</FONT>
            'keepevents', 0);
        
        % Process: Add time offset: -21.00ms for new arduino, -20 ms for old
        % arduino
        sFiles = bst_process('CallProcess', 'process_timeoffset', ...
            sFiles, [], ...
            'offset', -0.021, ...
            'overwrite', 0);
        
        
        % Process: DC offset correction: [-50ms,0ms]
        sFiles = bst_process('CallProcess', 'process_baseline', sFiles, [], ...
            'baseline',    [-0.05, 0], ...
            'sensortypes', 'EEG', ...
            'method',      'bl', ...  % DC offset correction:    x_std = x - &mu;
            'overwrite',   1);
        
        
    end % isubj
end %ipair


%% you can now make individual ERPs (you don't actually analyze it yourself, but it is used for do one more process for Alpha
% so this inspection is about what kind of data quality you are getting
% from this condition this subject. 

%% when you see the average ERP really noisy, it's recommended that you go back to single trial inspection and do 'reject bad channel' or 'reject trial' manually
% for these cases, you'd want to redo 'average, add time offset, and DC
% offset' again manually.

%% For alpha analysis, you do need one more Brainstorm process (do_bst_Duet_induced_alphaERD.m)