% do_0a_bst_linkraw_Duet.m

% Script generated by Brainstorm (03-Feb-2015)
% modified by Takako Fujioka 2015 March 3
% more modification for Duet study 2016 March 6
% brought back from Madeline's directory
% (Research/Motif_Piano_Duet/analysis_code) on 2019 01 27

% this will automatically make a new subject in the protocol and creat links to raw files, 
% but you have to import a
% channel file from 'channel_initial.mat'

%% for each pair, list the two people in the order that the filenames follow

% in Brainstorm make 'Duet2017' protocol

% this is where you store downloaded .cnt files (you have to change it
% yourself)
mydirname = "C:\Users\tfujioka\Documents\MATLAB\451C_W26_practice\raw\Piano_Duet2017";

% universal name

% list subj#1 subj#2 in the order of the file
pair = {
        'S01', 'S02';
        'S03', 'S04'; 
%         'S05', 'S06'; % S05 OUT for Alpha and FRN
%         'S07', 'S08'; % S07 S08 OUT for Alpha, IN for FRN
%         'S09', 'S10';
%         'S11', 'S12'; % S12 OUT for Alpha and FRN
%         'S13', 'S14';
%         'S15', 'S16'; % S15 S16 OUT for Alpha and FRN
%         'S17', 'S18';
%         'S19', 'S20';
%         'S21', 'S22'; % S21 S22 OUT for Alpha and FRN
%         'S23', 'S24';
        };    
npair = size(pair,1);

player = {'SubA';'SubB'};

%melnames states the combination of the score for each pair
% first line is first pair, second line is second pair and so on
melnames = [
    1,2,3,4; % pair 1
    3,4,1,2; % pair 2
%     1,2,3,4; % pair 3
%     3,4,1,2; % pair 4
%     1,2,3,4; % pair 5
%     3,4,1,2; % pair 6
%     1,2,3,4; % pair 7
%     3,4,1,2; % pair 8
%     1,2,3,4; % pair 9
%     3,4,1,2; % pair 10
%     1,2,3,4; % pair 11
%     3,4,1,2; % pair 12
     ];
npair = size(pair,1);

player = {'SubA';'SubB'};


for ipair = 1:npair

        sub={pair{ipair,1};pair{ipair,2}};
        pairname = sprintf('%s_%s', sub{1}, sub{2});
     
    for isubj=1:2
 
    RawFiles = {...
        sprintf('%s/%s/%s_AA%d_1_Data.cnt',mydirname, sub{isubj},sub{isubj},melnames(ipair,1)),...
        sprintf('%s/%s/%s_AA%d_2_Data.cnt',mydirname,sub{isubj},sub{isubj},melnames(ipair,1)),...
        sprintf('%s/%s/%s_BC%d_1_Data.cnt',mydirname,sub{isubj},sub{isubj},melnames(ipair,2)),...
        sprintf('%s/%s/%s_BC%d_2_Data.cnt',mydirname,sub{isubj},sub{isubj},melnames(ipair,2)),...
        sprintf('%s/%s/%s_AA%d_1_%s_Data.cnt',mydirname,sub{isubj},pairname,melnames(ipair,3),player{isubj}),...
        sprintf('%s/%s/%s_AA%d_2_%s_Data.cnt',mydirname,sub{isubj},pairname,melnames(ipair,3),player{isubj}),...
        sprintf('%s/%s/%s_BC%d_1_%s_Data.cnt',mydirname,sub{isubj},pairname,melnames(ipair,4),player{isubj}),...
        sprintf('%s/%s/%s_BC%d_2_%s_Data.cnt',mydirname,sub{isubj},pairname,melnames(ipair,4),player{isubj}),...
        };
    
     

    nraw = size(RawFiles,2);
    
    
        for iraw = 1:nraw

            % Input files
            sFiles = [];

            % Start a new report
            bst_report('Start', sFiles);

            % Process: Create link to raw file
            sFiles = bst_process('CallProcess', 'process_import_data_raw', ...
                sFiles, [], ...
                'subjectname', sub{isubj}, ...
                'datafile', {RawFiles{iraw}, 'EEG-NEUROSCAN-CNT'}, ...
                'channelreplace', 0, ...
                'channelalign', 0);

            % Save and display report
            ReportFile = bst_report('Save', sFiles);
            bst_report('Open', ReportFile);

        end
    end

 end

%% now import channel file from 'channel_initial.mat' because it is right now a wrong file 'CNT 2D channels (67)' 
% you have to import channels so that it has 'Neuroscan Quik-cap (67)'
