% do_0b_bst_ssp_Duet.m

% do_bst_ssp_2017Nov.m
% 2017 11 02 by Takako for Aury's analysis on the Duet data

% 2026 01 27 by Takako to offer a revised pipeline for 451C W26 analysis
% exercise

% Because the computation of SSP projectors are not anymore based on 
% blink epoched files, we are using only one of the continuous files
% to make projectors.

% Need to have detected eyeblinks within Brainstorm prior to this step

% Script generated by Brainstorm (18-May-2017)

% list subj#1 subj#2 in the order of the file
pair = {
        'S01', 'S02';
        'S03', 'S04'; 
%        'S05', 'S06'; % S05 OUT for Alpha and FRN
%         'S07', 'S08'; % S07 S08 OUT for Alpha, IN for FRN
%         'S09', 'S10';
%         'S11', 'S12'; % S12 OUT for Alpha and FRN
%         'S13', 'S14';
%         'S15', 'S16'; % S15 S16 OUT for Alpha and FRN
%         'S17', 'S18';
%         'S19', 'S20';
%         'S21', 'S22'; % S21 S22 OUT for Alpha and FRN
%         'S23', 'S24';
        };    
npair = size(pair,1);

player = {'SubA';'SubB'};


%first line is first pair, second line is second pair
melnames = [
    1,2,3,4; % pair 1
    3,4,1,2; % pair 2
%     1,2,3,4; % pair 3
%     3,4,1,2; % pair 4
%     1,2,3,4; % pair 5
%     3,4,1,2; % pair 6
%     1,2,3,4; % pair 7
%     3,4,1,2; % pair 8
%     1,2,3,4; % pair 9
%     3,4,1,2; % pair 10
%     1,2,3,4; % pair 11
%     3,4,1,2; % pair 12
    ];



% in this procedure only one raw file is looked at to do blink detections
% and SSP projector construction. All the other files can use these
% projectors later when epoching.
for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    for isubj= 1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        % List all the raw files for each subject
        % Input files

        % I am using only one of the 'computer-partner' files
        sFiles = {...
            sprintf('%s/@raw%s_AA%d_1_%s_Data/data_0raw_%s_AA%d_1_%s_Data.mat',subjname,pairname,melnames(ipair,3),playerID,pairname,melnames(ipair,3),playerID)};
        
        timeMax = 1800;
        
        
        % Start a new report
        bst_report('Start', sFiles);
        
        % Process: Detect eye blinks
        sFiles = bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
            'channelname', 'VEO', ...
            'timewindow',  [0, timeMax], ...
            'eventname',   'blinkv');
        
        % Process: Detect eye blinks
        sFiles = bst_process('CallProcess', 'process_evt_detect_eog', sFiles, [], ...
            'channelname', 'HEO', ...
            'timewindow',  [0, timeMax], ...
            'eventname',   'blinkh');
        
        % Process: SSP EOG: blinkv
        sFiles = bst_process('CallProcess', 'process_ssp_eog', sFiles, [], ...
            'eventname',   'blinkv', ...
            'sensortypes', 'EEG', ...
            'usessp',      1, ...
            'select',      1);
        
        % Process: SSP EOG: blinkh
        sFiles = bst_process('CallProcess', 'process_ssp_eog', sFiles, [], ...
            'eventname',   'blinkh', ...
            'sensortypes', 'EEG', ...
            'usessp',      1, ...
            'select',      1);
        
        % Save and display report
        ReportFile = bst_report('Save', sFiles);
        bst_report('Open', ReportFile);
        % bst_report('Export', ReportFile, ExportDir);
        
    end % subj
end % pair

%% after this you should look at the projectors and make a good selections. 
% Remember, the effective projectors are straight line splits
% Also, an isolated small spot for one electrode is important