% do_1c_bst_import_continuous_DuetEx.m

% Script generated by Brainstorm (14-Jul-2021)
% Run this while Brainstorm opened

% this script imports the each of entire continuous file while applying SSP
% (eye artifact removal)

% universal name
% list subj#1 subj#2 in the order of the file
pair = {
        'S01', 'S02';
        'S03', 'S04'; 
%         'S05', 'S06'; % S05 OUT for Alpha and FRN
%         'S07', 'S08'; % S07 S08 OUT for Alpha, IN for FRN
%         'S09', 'S10';
%         'S11', 'S12'; % S12 OUT for Alpha and FRN
%         'S13', 'S14';
%         'S15', 'S16'; % S15 S16 OUT for Alpha and FRN
%         'S17', 'S18';
%         'S19', 'S20';
%         'S21', 'S22'; % S21 S22 OUT for Alpha and FRN
%         'S23', 'S24';
        };    
npair = size(pair,1);

player = {'SubA';'SubB'};

%melnames states the combination of the score for each pair
% first line is first pair, second line is second pair and so on
melnames = [
    1,2,3,4; % pair 1
    3,4,1,2; % pair 2
%     1,2,3,4; % pair 3
%     3,4,1,2; % pair 4
%     1,2,3,4; % pair 5
%     3,4,1,2; % pair 6
%     1,2,3,4; % pair 7
%     3,4,1,2; % pair 8
%     1,2,3,4; % pair 9
%     3,4,1,2; % pair 10
%     1,2,3,4; % pair 11
%     3,4,1,2; % pair 12
     ];
npair = size(pair,1);

player = {'SubA';'SubB'};

for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    % loop two partners
    for isubj=1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        sFiles = {...
            sprintf('%s/@raw%s_AA%d_1_Data/data_0raw_%s_AA%d_1_Data.mat',subjname,subjname,melnames(ipair,1),subjname,melnames(ipair,1)), ...
            sprintf('%s/@raw%s_AA%d_2_Data/data_0raw_%s_AA%d_2_Data.mat',subjname,subjname,melnames(ipair,1),subjname,melnames(ipair,1)), ...
            sprintf('%s/@raw%s_BC%d_1_Data/data_0raw_%s_BC%d_1_Data.mat',subjname,subjname,melnames(ipair,2),subjname,melnames(ipair,2)), ...
            sprintf('%s/@raw%s_BC%d_2_Data/data_0raw_%s_BC%d_2_Data.mat',subjname,subjname,melnames(ipair,2),subjname,melnames(ipair,2)), ...
            sprintf('%s/@raw%s_AA%d_1_%s_Data/data_0raw_%s_AA%d_1_%s_Data.mat',subjname,pairname,melnames(ipair,3),playerID,pairname,melnames(ipair,3),playerID), ...
            sprintf('%s/@raw%s_AA%d_2_%s_Data/data_0raw_%s_AA%d_2_%s_Data.mat',subjname,pairname,melnames(ipair,3),playerID,pairname,melnames(ipair,3),playerID), ...
            sprintf('%s/@raw%s_BC%d_1_%s_Data/data_0raw_%s_BC%d_1_%s_Data.mat',subjname,pairname,melnames(ipair,4),playerID,pairname,melnames(ipair,4),playerID), ...
            sprintf('%s/@raw%s_BC%d_2_%s_Data/data_0raw_%s_BC%d_2_%s_Data.mat',subjname,pairname,melnames(ipair,4),playerID,pairname,melnames(ipair,4),playerID), ...
            };
        

% Start a new report
bst_report('Start', sFiles);

% Process: Import MEG/EEG: Time
sFiles = bst_process('CallProcess', 'process_import_data_time', sFiles, [], ...
    'subjectname', subjname, ...
    'condition',   '', ...
    'timewindow',  [], ...
    'split',       0, ...
    'ignoreshort', 0, ...
    'usectfcomp',  0, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    []);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
    end % isubj
end % ipair
