% do_01b_bst_import_trigger_DuetEx.m

% running while opening the protocol 'Duet2017'

% modifiying for DuetReverb (451C W22)
% DuetDistance (451C W24) 2024-03-10
% Sunday, I am missing TF SubB 05

% modifying for Duet excersize (451C w26) 2026-01-27

% universal name
% list subj#1 subj#2 in the order of the file
pair = {
        'S01', 'S02';
        'S03', 'S04'; 
%         'S05', 'S06'; % S05 OUT for Alpha and FRN
%         'S07', 'S08'; % S07 S08 OUT for Alpha, IN for FRN
%         'S09', 'S10';
%         'S11', 'S12'; % S12 OUT for Alpha and FRN
%         'S13', 'S14';
%         'S15', 'S16'; % S15 S16 OUT for Alpha and FRN
%         'S17', 'S18';
%         'S19', 'S20';
%         'S21', 'S22'; % S21 S22 OUT for Alpha and FRN
%         'S23', 'S24';
        };    
npair = size(pair,1);

player = {'SubA';'SubB'};

%melnames states the combination of the score for each pair
% first line is first pair, second line is second pair and so on
melnames = [
    1,2,3,4; % pair 1
    3,4,1,2; % pair 2
%     1,2,3,4; % pair 3
%     3,4,1,2; % pair 4
%     1,2,3,4; % pair 5
%     3,4,1,2; % pair 6
%     1,2,3,4; % pair 7
%     3,4,1,2; % pair 8
%     1,2,3,4; % pair 9
%     3,4,1,2; % pair 10
%     1,2,3,4; % pair 11
%     3,4,1,2; % pair 12
     ];
npair = size(pair,1);

player = {'SubA';'SubB'};


% loop all the pairs
for ipair=1:npair
    sub={pair{ipair,1};pair{ipair,2}};
    pairname = sprintf('%s_%s', sub{1}, sub{2});
    
    % loop two partners
    for isubj=1:2
        
        subjname = sub{isubj};
        playerID= player{isubj};
        
        display(playerID)
        All_sFiles = {
            sprintf('%s/@raw%s_AA%d_1_Data/data_0raw_%s_AA%d_1_Data.mat',subjname,subjname,melnames(ipair,1),subjname,melnames(ipair,1)), ...
            sprintf('%s/@raw%s_AA%d_2_Data/data_0raw_%s_AA%d_2_Data.mat',subjname,subjname,melnames(ipair,1),subjname,melnames(ipair,1)), ...
            sprintf('%s/@raw%s_BC%d_1_Data/data_0raw_%s_BC%d_1_Data.mat',subjname,subjname,melnames(ipair,2),subjname,melnames(ipair,2)), ...
            sprintf('%s/@raw%s_BC%d_2_Data/data_0raw_%s_BC%d_2_Data.mat',subjname,subjname,melnames(ipair,2),subjname,melnames(ipair,2)), ...
            sprintf('%s/@raw%s_AA%d_1_%s_Data/data_0raw_%s_AA%d_1_%s_Data.mat',subjname,pairname,melnames(ipair,3),playerID,pairname,melnames(ipair,3),playerID), ...
            sprintf('%s/@raw%s_AA%d_2_%s_Data/data_0raw_%s_AA%d_2_%s_Data.mat',subjname,pairname,melnames(ipair,3),playerID,pairname,melnames(ipair,3),playerID), ...
            sprintf('%s/@raw%s_BC%d_1_%s_Data/data_0raw_%s_BC%d_1_%s_Data.mat',subjname,pairname,melnames(ipair,4),playerID,pairname,melnames(ipair,4),playerID), ...
            sprintf('%s/@raw%s_BC%d_2_%s_Data/data_0raw_%s_BC%d_2_%s_Data.mat',subjname,pairname,melnames(ipair,4),playerID,pairname,melnames(ipair,4),playerID), ...
            };
        nfile=size(All_sFiles,2);
        
        
        for ifile =1:nfile
            % current event file RawFiles
            
            % Linux now (it didn't run without .mat)
            %event_filename=sprintf('/user/t/takako/MATLAB/Duet/eeg_analysis/Duet2022/EventFiles/events_%s_run%d.mat',subjname, ifile);
            
            % PC (it didn't run without .mat)
            event_filename=sprintf('/Volumes/MLF/EEG-Hyperscanning/EventFiles/events_%s_run%d.mat',subjname, ifile);
             
            RawFiles = {...
                event_filename;
                };
            
            % nofile? skip
            if ~exist(event_filename) 
                display(sprintf('%s: file not found', event_filename)); 
                continue;
            end
            
            
            % Script generated by Brainstorm (14-Jul-2021)
            % Start a new report
            % bst_report('Start', sFiles);      
          

            % EEG raw file
            my_current_eegfile = All_sFiles{ifile};

            sFiles = {...
                my_current_eegfile;
                };


            % Process: Import from file
            sFiles = bst_process('CallProcess', 'process_evt_import', sFiles, [], ...
                'evtfile', {RawFiles{1}, 'BST'}, ...
                'evtname', '', ...
                'delete',  0);
            
%             % Save and display report
%             ReportFile = bst_report('Save', sFiles);
%             bst_report('Open', ReportFile);
            % bst_report('Export', ReportFile, ExportDir);
            
        end % ifile
    end % isubj
end % ipair
